apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: mysql-secret-engine
  namespace: dev
spec:
  vaultRef:
    name: vault
    namespace: demo
  mysql:
    databaseRef:
      name: my-group
      namespace: demo