apiVersion: kubevault.com/v1alpha2
kind: VaultServer
metadata:
  name: vault-3
  namespace: demo
spec:
  replicas: 1
  version: 1.10.3
  backend:
    inmem: {}
  unsealer:
    secretShares: 4
    secretThreshold: 2
    mode:
      kubernetesSecret:
        secretName: vault-keys