apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  annotations:
    meta.helm.sh/release-name: virtual-secrets
    meta.helm.sh/release-namespace: virtual-secrets
  labels:
    app.kubernetes.io/instance: virtual-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: virtual-secrets
    app.kubernetes.io/version: v0.0.1
    helm.sh/chart: virtual-secrets-v2025.1.1
  name: v1alpha1.virtual-secrets.dev
spec:
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lRRUR0aEZHRzA2aVRPNmczYXZLTUVnekFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TlRBeE1UVXhNREl4TURWYUZ3MHpOVEF4TVRNeE1ESXhNRFZhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE4dnk5CmIwWUw4aVlIMFhEKy9pODMrMjRaNndncklqWksycTFUZWwzZFJoWHVBZmYrOUVaRzJSK1dGYzg5Vm9YTjI5c20KdnNkNmUyMXNLcjFMOGdMd0M0cWFKdmpqTEVaak9takE2UFpvbUJMNnlLa2RydXRCNzRjZXBTL1dJSG0wOGx1MQp6K1l1V2pRZkxlSnNiVVp5RHY2UXZ1MEljYXphT0JlT0JNWkxTbDRwdE1XWGVkNmZiMXovMUFxSzkwaXF4czFRCmJUbm1WTlVTZEJqTDQrcHltRUlKQU5XdUsrZXMvV3lGblJlWWJmUzlCSTJEbDI0RDk2SGNoQkpPanlIKzhUczQKTHAwQlJEc3o1a3RzQTlFa3ZGR1NuQzF2dURCNGdxOWtKSzRzY3BLOHRiM1dvNThNZnZxZXdvb1BRbVArQzdOWQpxK25tWEhweEpJRi9rT0ZUSVFJREFRQUJvMkV3WHpBT0JnTlZIUThCQWY4RUJBTUNBcVF3SFFZRFZSMGxCQll3CkZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUUKRkU0bDVNZGNZalBiejFOdUp5b2J4ZjZaYUJIRE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmdLRE14bTRDSgptWWg3WkYreUhkNEo1NG5tc05jMjhjcEt3cDEyVVhNVFo0TlNpR0JMaUlkQXlmeXEzbkQzVlYwZXVSTjQxeTVLCmVWN1Btak1YZkFFaTlTRnhGeGwwOGQ2bVZMdHJadTh6eHZDRE00WXljZWVEK2pPS2VnZktpRVk5STJXOCtSQnYKc0J3bmdncTNMTFE4d3ZmUVh4bDhUUHBLb0pPbHA3SHREd1FMc0JCT2tiOE5uaU5RQTQrejkxS1FNTkpEdkR4cwpjT1lRaVhsdWlRZ1BDSTFRelBsT2srZzNkTTVRL1pUc2ZMdFI2bXdhQmNXNG9lZ3drb0srTHE0OHREVytSa2JlCjlmc3dxa3lVYmZLb1NHSDNiME01ZiswNEc3MFU1NEREcmUyeDUwK3I4eWhmb2ZrVUI3dHB6dDRKa0FUV0F3Y1kKTGlVaEZQekVVYzZsCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  group: virtual-secrets.dev
  groupPriorityMinimum: 10000
  service:
    name: virtual-secrets
    namespace: virtual-secrets
    port: 443
  version: v1alpha1
  versionPriority: 15
