apiVersion: kubedb.com/v1
kind: Postgres
metadata:
  name: pg-demo
  namespace: demo
spec:
#  authSecret:
#    apiGroup: "virtual-secrets.dev"
#    secretStoreName: aws
  replicas: 3
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  storageType: Ephemeral
  deletionPolicy: Delete
  version: "13.13"