apiVersion: virtual-secrets.dev/v1alpha1
kind: Secret
metadata:
  name: my-secret
  namespace: demo
#data:
#  username: YWRtaW4K
#  password: YWJjZGUK
stringData:
  username: tapojit
  password: paul1
  hello: world
##  a: xxxx
secretStoreName: vault
