apiVersion: virtual-secrets.dev/v1alpha1
kind: Secret
metadata:
  name: your-secret
  namespace: demo-1
data:
 username: YWRtaW4K
 password: YWJjZGUK
stringData:
  username: tapojit
  password: paul
  hello: world
##  a: xxxx
#secretStoreName: vault
secretStoreName: aws
