apiVersion: engine.kubevault.com/v1alpha1
kind: SecretAccessRequest
metadata:
  name: redis-cred-req
  namespace: demo
spec:
  roleRef:
    kind: RedisRole
    name: write-read-role
    namespace: demo
  subjects:
    - kind: ServiceAccount
      name: test-user-account
      namespace: demo