apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  creationTimestamp: null
  name: secret-provider-class
  namespace: demo
spec:
  parameters:
    objects: |
      - objectName: redis-creds-username
        secretKey: username
        secretPath: /k8s.da431e02-d3ad-46da-9666-379934ec98e0.redis.demo.redis-secret-engine/creds/k8s.da431e02-d3ad-46da-9666-379934ec98e0.demo.write-read-role
      - objectName: redis-creds-password
        secretKey: password
        secretPath: /k8s.da431e02-d3ad-46da-9666-379934ec98e0.redis.demo.redis-secret-engine/creds/k8s.da431e02-d3ad-46da-9666-379934ec98e0.demo.write-read-role
    roleName: k8s.da431e02-d3ad-46da-9666-379934ec98e0.demo.srb-demo-secret-role-binding
    vaultAddress: http://vault.demo:8200
    vaultSkipTLSVerify: "true"
  provider: vault
status: {}
